FROM apache/flink-statefun:3.2.0-java11

RUN mkdir -p /opt/statefun/modules/statefun-application
COPY target/statefun-application-*jar-with-dependencies.jar /opt/statefun/modules/statefun-application/